### ISSUE TITLE
Melhorar tela de listagem de abrigos (dashboard)

### ISSUE THREAD

**Issue by cpt-westphalen** [AnaWestphalen/gestor-abrigo-pet#43]
A tela inicial do usuário é uma listagem dos abrigos a que ele está vinculado e um botão de ação para ir pra criação de um novo abrigo.

A tela é uma lista simples, mas poderia ser uma grade de cards com a imagem do abrigo. O botão de ação poderia ser um FAB grande em baixo ou em cima da tela, talvez flutuante? Não sei.

É uma tela que precisa ser melhorada.

**Comment by flaviaadiniz** [comment]
PR for the changes related to this issue: ` https://github.com/AnaWestphalen/gestor-abrigo-pet/pull/53`
